#pragma once

#include "../../../../vulkan/objects/VkObjects.hpp"

enum PipelineStage {
	NONE = VK_PIPELINE_STAGE_NONE,
	TOP_OF_PIPE = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
	DRAW_INDIRECT = VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT,
	INDEX_INPUT = VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT,
	VERTEX_ATTRIBUTE = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,
	EARLY_FRAGMENT = VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
	FRAGMENT_SHADER = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
	LATE_FRAGMENT = VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
	COLOR_OUTPUT = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
	BOTTOM_OF_PIPE = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT
};
typedef std::uint32_t PipelineStageFlags;

enum AccessBit {
	NONE = VK_ACCESS_NONE,
	INDIRECT_COMMAND = VK_ACCESS_INDIRECT_COMMAND_READ_BIT,
	INDEX_READ = VK_ACCESS_INDEX_READ_BIT,
	VERTEX_ATTRIBUTE_READ = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT,
	UNIFORM_READ = VK_ACCESS_UNIFORM_READ_BIT,
	INPUT_ATTACHMENT_READ = VK_ACCESS_INPUT_ATTACHMENT_READ_BIT,
	SHADER_READ = VK_ACCESS_SHADER_READ_BIT,
	SHADER_WRITE = VK_ACCESS_SHADER_WRITE_BIT,
	COLOR_READ = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT,
	COLOR_WRITE = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
	DEPTH_STENCIL_READ = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT,
	DEPTH_STENCIL_WRITE = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
	TRANSFER_READ = VK_ACCESS_TRANSFER_READ_BIT,
	TRANSFER_WRITE = VK_ACCESS_TRANSFER_WRITE_BIT
};
typedef std::uint32_t AccessFlags;