#pragma once

#include "../../../../vulkan/objects/VkObjects.hpp"

enum ImageType { 
	COLOR = 0x1, 
	DEPTH = 0x2
};
typedef std::uint32_t ImageTypeFlags;

enum ImageFormat {
	RGBA16 = VK_FORMAT_R16G16B16A16_SFLOAT,
	RGBA8 = VK_FORMAT_R8G8B8A8_UNORM,
	B10GR11_PACK32 = VK_FORMAT_B10G11R11_UFLOAT_PACK32,
	R8 = VK_FORMAT_R8_UNORM,
	D32 = VK_FORMAT_D32_SFLOAT,
	RG32 = VK_FORMAT_R32G32_SFLOAT,
	RG16_SNORM = VK_FORMAT_R16G16_SNORM
};

enum ImageUsage {
	COLOR = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,
	DEPTH_STENCIL = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
	INPUT_ATTACHMENT = VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT,
	SAMPLED = VK_IMAGE_USAGE_SAMPLED_BIT,
	TRANSFER_SRC = VK_IMAGE_USAGE_TRANSFER_SRC_BIT,
	TRANSFER_DST = VK_IMAGE_USAGE_TRANSFER_DST_BIT
};
typedef std::uint32_t ImageUsageFlags;

enum ImageAspect {
	COLOR = VK_IMAGE_ASPECT_COLOR_BIT,
	DEPTH = VK_IMAGE_ASPECT_DEPTH_BIT,
	STENCIL = VK_IMAGE_ASPECT_STENCIL_BIT
};

enum ImageLayout {
	UNDEFINED = VK_IMAGE_LAYOUT_UNDEFINED,
	COLOR = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
	DEPTH = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
	DEPTH_READ_ONLY = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
	DEPTH_STENCIL = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
	DEPTH_STENCIL_READ_ONLY = VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL,
	TRANSFER_SRC = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
	TRANSFER_DST = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
	SHADER_READ_ONLY = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
	PRESENT = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR
};

enum ImageCreate {
	NONE = 0x0,
	CUBE_COMPATIBLE = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT,
	ARRAY_2D_COMPATIBLE = VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT
};
typedef std::uint32_t ImageCreateFlags;

enum ImageSamples {
	ONE = VK_SAMPLE_COUNT_1_BIT,
	TWO = VK_SAMPLE_COUNT_2_BIT,
	FOUR = VK_SAMPLE_COUNT_4_BIT,
	EIGHT = VK_SAMPLE_COUNT_8_BIT,
	SIXTEEN = VK_SAMPLE_COUNT_16_BIT
};

enum ImageViewType {
	TYPE_2D = VK_IMAGE_VIEW_TYPE_2D,
	TYPE_CUBE = VK_IMAGE_VIEW_TYPE_CUBE,
	TYPE_2D_ARRAY = VK_IMAGE_VIEW_TYPE_2D_ARRAY,
	TYPE_CUBE_ARRAY = VK_IMAGE_VIEW_TYPE_CUBE_ARRAY
};

enum TextureUse { 
	NONE,
	ATTACHMENT_LOAD, // Indicates the texture will be loaded as an attachment for a future pass
	TEXTURE_SAMPLE   // Indicates the texture will be sampled in a shader in a future pass
};
typedef std::uint32_t TextureUseFlags;

enum ExtentRatio {
	CUSTOM,
	SWAPCHAIN,
	HALF_SWAPCHAIN,
	QUARTER_SWAPCHAIN
};

struct TextureDesc {
	ImageFormat format;
	ImageUsageFlags usage;
	ImageAspect aspect = ImageAspect::COLOR;
};