#pragma once

#include "objects/impl/renderPasses/ForwardPass.hpp"
#include "objects/impl/renderPasses/DeferredWritingPass.hpp"
#include "objects/impl/renderPasses/DeferredShadingPass.hpp"
#include "objects/impl/renderPasses/ShadowPass.hpp"
#include "objects/impl/renderPasses/GUIPass.hpp"
#include "objects/impl/renderPasses/SunViewPass.hpp"
#include "objects/impl/renderPasses/PostProcessPass.hpp"
#include "objects/impl/renderPasses/TonemapPass.hpp"
#include "objects/impl/renderPasses/PreSSAOPass.hpp"
#include "objects/impl/renderPasses/SSAOPass.hpp"
#include "objects/impl/renderPasses/DebugPass.hpp"

#include "objects/impl/pipelineLayouts/ForwardPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/DeferredWritingPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/DeferredShadingPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/ShadowPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/CubemapShadowPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/LineDebugPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/DebugViewsPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/OverVisualisationPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/BloomPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/CompositionPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/MosaicPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/SunViewPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/TonemapPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/PreSSAOPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/SSAOPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/SSAOBlurPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/SkyboxPipelineLayout.hpp"
#include "objects/impl/pipelineLayouts/SunPipelineLayout.hpp"

#include "objects/impl/pipelines/ForwardPipeline.hpp"
#include "objects/impl/pipelines/DeferredWritingPipeline.hpp"
#include "objects/impl/pipelines/DeferredShadingPipeline.hpp"
#include "objects/impl/pipelines/ShadowPipeline.hpp"
#include "objects/impl/pipelines/CubemapShadowPipeline.hpp"
#include "objects/impl/pipelines/LineDebugPipeline.hpp"
#include "objects/impl/pipelines/DebugViewsPipeline.hpp"
#include "objects/impl/pipelines/OverVisualisationPipeline.hpp"
#include "objects/impl/pipelines/MosaicPipeline.hpp"
#include "objects/impl/pipelines/BloomPipeline.hpp"
#include "objects/impl/pipelines/CompositionPipeline.hpp"
#include "objects/impl/pipelines/SunViewPipeline.hpp"
#include "objects/impl/pipelines/TonemapPipeline.hpp"
#include "objects/impl/pipelines/FXAAPipeline.hpp"
#include "objects/impl/pipelines/PreSSAOPipeline.hpp"
#include "objects/impl/pipelines/SSAOPipeline.hpp"
#include "objects/impl/pipelines/SSAOBlurPipeline.hpp"
#include "objects/impl/pipelines/SkyboxPipeline.hpp"
#include "objects/impl/pipelines/SunPipeline.hpp"

#include "objects/impl/textureBuffers/DepthTextureBuffer.hpp"
#include "objects/impl/textureBuffers/CubemapTextureBuffer.hpp"
#include "objects/impl/textureBuffers/CubemapArrayDepthTextureBuffer.hpp"
#include "objects/impl/textureBuffers/ArrayColourTextureBuffer.hpp"
#include "objects/impl/textureBuffers/ArrayDepthTextureBuffer.hpp"
#include "objects/impl/textureBuffers/ColourTextureBuffer.hpp"
#include "objects/impl/textureBuffers/NoiseTextureBuffer.hpp"

#include "objects/impl/framebuffers/ForwardFramebuffer.hpp"
#include "objects/impl/framebuffers/DeferredWritingFramebuffer.hpp"
#include "objects/impl/framebuffers/DeferredShadingFramebuffer.hpp"
#include "objects/impl/framebuffers/ShadowFramebuffer.hpp"
#include "objects/impl/framebuffers/CubemapFramebuffer.hpp"
#include "objects/impl/framebuffers/CubemapArrayFramebuffer.hpp"
#include "objects/impl/framebuffers/ArrayFramebuffer.hpp"
#include "objects/impl/framebuffers/GUIFramebuffer.hpp"
#include "objects/impl/framebuffers/SunFramebuffer.hpp"
#include "objects/impl/framebuffers/WriteToTargetFramebuffer.hpp"
#include "objects/impl/framebuffers/PreSSAOFramebuffer.hpp"
#include "objects/impl/framebuffers/DebugFramebuffer.hpp"

#include "objects/impl/descriptorSets/BufferDescriptorSet.hpp"
#include "objects/impl/descriptorSets/ImageDescriptorSet.hpp"
#include "objects/impl/descriptorSets/ArrayImageDescriptorSet.hpp"

#include "preProcess/SSAOPreProcess.hpp"

#include "postProcessing/BloomPostProcess.hpp"
#include "postProcessing/TonemapPostProcess.hpp"
#include "postProcessing/FXAAPostProcess.hpp"
#include "postProcessing/MosaicPostProcess.hpp"